apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-web.fullname" . }}
  labels:
    {{- include "static-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "static-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
        {{- range .Values.files }}
          - name: content
            mountPath: "/usr/share/nginx/html/{{ .folder }}/{{ .name }}"
            subPath: "{{ .name }}"
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: content
          configMap:
            name: static-web-configmap